version: "3"
services:
  back:
    build: ./back
    ports:
      - "4321:4321"
    working_dir: /home/blog/back
    command: bash "./entrypoint.sh"
    volumes:
      - ./back:/home/blog/back

  front:
    build: ./front
    ports:
      - "5173:5173"
    working_dir: /home/blog/front
    command: bash "./entrypoint.sh"
    volumes:
      - ./front:/home/blog/front

  db:
    image: mysql:8.0.30-debian
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3