version: "3"
services:
  back:
    build: ./back
    ports:
      - "4321:4321"
    working_dir: /home/node/back
    command: bash "./entrypoint.sh"
    volumes:
      - ./back:/home/node/back
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "localhost:4321/ping" ]
    #   interval: 20s
    #   timeout: 20s
    #   retries: 5
    depends_on:
      db:
        condition: service_healthy

  front:
    build: ./front
    ports:
      - "5173:5173"
    working_dir: /home/node/front
    command: bash "./entrypoint.sh"
    volumes:
      - ./front:/home/node/front
    # depends_on:
    #   back:
    #     condition: service_healthy

  db:
    image: mysql:8.0.30-debian
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
